/* eslint-disable */
// This file is auto-generated by frontend/scripts/generate-api-client.mjs.
// Do not edit manually.

const DEFAULT_BACKEND_URL = "http://localhost:3000";

export const routeManifest = {
  "patchSystemResetCooldown": {"path":"/system/reset-cooldown","openapiPath":"/system/reset-cooldown","method":"PATCH","operationId":"patchSystemResetCooldown","tag":"System","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "patchSystemAvailabilityTimeout": {"path":"/system/availability-timeout","openapiPath":"/system/availability-timeout","method":"PATCH","operationId":"patchSystemAvailabilityTimeout","tag":"System","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "patchSystemJobStartWindow": {"path":"/system/job-start-window","openapiPath":"/system/job-start-window","method":"PATCH","operationId":"patchSystemJobStartWindow","tag":"System","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "patchSystemNegotiationWindow": {"path":"/system/negotiation-window","openapiPath":"/system/negotiation-window","method":"PATCH","operationId":"patchSystemNegotiationWindow","tag":"System","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "postAuthResetsResetToken": {"path":"/auth/resets/:resetToken","openapiPath":"/auth/resets/{resetToken}","method":"POST","operationId":"postAuthResetsResetToken","tag":"Auth","pathParams":["resetToken"],"bodyKind":"json","multipartFileField":null},
  "postAuthResets": {"path":"/auth/resets","openapiPath":"/auth/resets","method":"POST","operationId":"postAuthResets","tag":"Auth","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "postAuthTokens": {"path":"/auth/tokens","openapiPath":"/auth/tokens","method":"POST","operationId":"postAuthTokens","tag":"Auth","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "postUsers": {"path":"/users","openapiPath":"/users","method":"POST","operationId":"postUsers","tag":"Users","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getUsers": {"path":"/users","openapiPath":"/users","method":"GET","operationId":"getUsers","tag":"Users","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "getUsersMe": {"path":"/users/me","openapiPath":"/users/me","method":"GET","operationId":"getUsersMe","tag":"Users","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "putUsersMeAvatar": {"path":"/users/me/avatar","openapiPath":"/users/me/avatar","method":"PUT","operationId":"putUsersMeAvatar","tag":"Users","pathParams":[],"bodyKind":"multipart","multipartFileField":"file"},
  "putUsersMeResume": {"path":"/users/me/resume","openapiPath":"/users/me/resume","method":"PUT","operationId":"putUsersMeResume","tag":"Users","pathParams":[],"bodyKind":"multipart","multipartFileField":"file"},
  "patchUsersUserIdSuspended": {"path":"/users/:userId/suspended","openapiPath":"/users/{userId}/suspended","method":"PATCH","operationId":"patchUsersUserIdSuspended","tag":"Users","pathParams":["userId"],"bodyKind":"json","multipartFileField":null},
  "patchUsersMe": {"path":"/users/me","openapiPath":"/users/me","method":"PATCH","operationId":"patchUsersMe","tag":"Users","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "patchUsersMeAvailable": {"path":"/users/me/available","openapiPath":"/users/me/available","method":"PATCH","operationId":"patchUsersMeAvailable","tag":"Users","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getUsersMeInvitations": {"path":"/users/me/invitations","openapiPath":"/users/me/invitations","method":"GET","operationId":"getUsersMeInvitations","tag":"Users","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "getUsersMeInterests": {"path":"/users/me/interests","openapiPath":"/users/me/interests","method":"GET","operationId":"getUsersMeInterests","tag":"Users","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "getUsersMeQualifications": {"path":"/users/me/qualifications","openapiPath":"/users/me/qualifications","method":"GET","operationId":"getUsersMeQualifications","tag":"Users","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "postBusinesses": {"path":"/businesses","openapiPath":"/businesses","method":"POST","operationId":"postBusinesses","tag":"Businesses","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getBusinesses": {"path":"/businesses","openapiPath":"/businesses","method":"GET","operationId":"getBusinesses","tag":"Businesses","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "getBusinessesMe": {"path":"/businesses/me","openapiPath":"/businesses/me","method":"GET","operationId":"getBusinessesMe","tag":"Businesses","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "patchBusinessesMe": {"path":"/businesses/me","openapiPath":"/businesses/me","method":"PATCH","operationId":"patchBusinessesMe","tag":"Businesses","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getBusinessesMeJobs": {"path":"/businesses/me/jobs","openapiPath":"/businesses/me/jobs","method":"GET","operationId":"getBusinessesMeJobs","tag":"Businesses","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "postBusinessesMeJobs": {"path":"/businesses/me/jobs","openapiPath":"/businesses/me/jobs","method":"POST","operationId":"postBusinessesMeJobs","tag":"Businesses","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "patchBusinessesMeJobsJobId": {"path":"/businesses/me/jobs/:jobId","openapiPath":"/businesses/me/jobs/{jobId}","method":"PATCH","operationId":"patchBusinessesMeJobsJobId","tag":"Businesses","pathParams":["jobId"],"bodyKind":"json","multipartFileField":null},
  "deleteBusinessesMeJobsJobId": {"path":"/businesses/me/jobs/:jobId","openapiPath":"/businesses/me/jobs/{jobId}","method":"DELETE","operationId":"deleteBusinessesMeJobsJobId","tag":"Businesses","pathParams":["jobId"],"bodyKind":null,"multipartFileField":null},
  "putBusinessesMeAvatar": {"path":"/businesses/me/avatar","openapiPath":"/businesses/me/avatar","method":"PUT","operationId":"putBusinessesMeAvatar","tag":"Businesses","pathParams":[],"bodyKind":"multipart","multipartFileField":"file"},
  "getBusinessesBusinessId": {"path":"/businesses/:businessId","openapiPath":"/businesses/{businessId}","method":"GET","operationId":"getBusinessesBusinessId","tag":"Businesses","pathParams":["businessId"],"bodyKind":null,"multipartFileField":null},
  "patchBusinessesBusinessIdVerified": {"path":"/businesses/:businessId/verified","openapiPath":"/businesses/{businessId}/verified","method":"PATCH","operationId":"patchBusinessesBusinessIdVerified","tag":"Businesses","pathParams":["businessId"],"bodyKind":"json","multipartFileField":null},
  "postPositionTypes": {"path":"/position-types","openapiPath":"/position-types","method":"POST","operationId":"postPositionTypes","tag":"Position Types","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getPositionTypes": {"path":"/position-types","openapiPath":"/position-types","method":"GET","operationId":"getPositionTypes","tag":"Position Types","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "patchPositionTypesPositionTypeId": {"path":"/position-types/:positionTypeId","openapiPath":"/position-types/{positionTypeId}","method":"PATCH","operationId":"patchPositionTypesPositionTypeId","tag":"Position Types","pathParams":["positionTypeId"],"bodyKind":"json","multipartFileField":null},
  "deletePositionTypesPositionTypeId": {"path":"/position-types/:positionTypeId","openapiPath":"/position-types/{positionTypeId}","method":"DELETE","operationId":"deletePositionTypesPositionTypeId","tag":"Position Types","pathParams":["positionTypeId"],"bodyKind":null,"multipartFileField":null},
  "getQualifications": {"path":"/qualifications","openapiPath":"/qualifications","method":"GET","operationId":"getQualifications","tag":"Qualifications","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "postQualifications": {"path":"/qualifications","openapiPath":"/qualifications","method":"POST","operationId":"postQualifications","tag":"Qualifications","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getQualificationsQualificationId": {"path":"/qualifications/:qualificationId","openapiPath":"/qualifications/{qualificationId}","method":"GET","operationId":"getQualificationsQualificationId","tag":"Qualifications","pathParams":["qualificationId"],"bodyKind":null,"multipartFileField":null},
  "patchQualificationsQualificationId": {"path":"/qualifications/:qualificationId","openapiPath":"/qualifications/{qualificationId}","method":"PATCH","operationId":"patchQualificationsQualificationId","tag":"Qualifications","pathParams":["qualificationId"],"bodyKind":"json","multipartFileField":null},
  "putQualificationsQualificationIdDocument": {"path":"/qualifications/:qualificationId/document","openapiPath":"/qualifications/{qualificationId}/document","method":"PUT","operationId":"putQualificationsQualificationIdDocument","tag":"Qualifications","pathParams":["qualificationId"],"bodyKind":"multipart","multipartFileField":"file"},
  "getJobs": {"path":"/jobs","openapiPath":"/jobs","method":"GET","operationId":"getJobs","tag":"Jobs","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "getJobsJobId": {"path":"/jobs/:jobId","openapiPath":"/jobs/{jobId}","method":"GET","operationId":"getJobsJobId","tag":"Jobs","pathParams":["jobId"],"bodyKind":null,"multipartFileField":null},
  "patchJobsJobIdNoShow": {"path":"/jobs/:jobId/no-show","openapiPath":"/jobs/{jobId}/no-show","method":"PATCH","operationId":"patchJobsJobIdNoShow","tag":"Jobs","pathParams":["jobId"],"bodyKind":"json","multipartFileField":null},
  "patchJobsJobIdInterested": {"path":"/jobs/:jobId/interested","openapiPath":"/jobs/{jobId}/interested","method":"PATCH","operationId":"patchJobsJobIdInterested","tag":"Jobs","pathParams":["jobId"],"bodyKind":"json","multipartFileField":null},
  "getJobsJobIdInterests": {"path":"/jobs/:jobId/interests","openapiPath":"/jobs/{jobId}/interests","method":"GET","operationId":"getJobsJobIdInterests","tag":"Jobs","pathParams":["jobId"],"bodyKind":null,"multipartFileField":null},
  "getJobsJobIdCandidates": {"path":"/jobs/:jobId/candidates","openapiPath":"/jobs/{jobId}/candidates","method":"GET","operationId":"getJobsJobIdCandidates","tag":"Jobs","pathParams":["jobId"],"bodyKind":null,"multipartFileField":null},
  "getJobsJobIdCandidatesUserId": {"path":"/jobs/:jobId/candidates/:userId","openapiPath":"/jobs/{jobId}/candidates/{userId}","method":"GET","operationId":"getJobsJobIdCandidatesUserId","tag":"Jobs","pathParams":["jobId","userId"],"bodyKind":null,"multipartFileField":null},
  "patchJobsJobIdCandidatesUserIdInterested": {"path":"/jobs/:jobId/candidates/:userId/interested","openapiPath":"/jobs/{jobId}/candidates/{userId}/interested","method":"PATCH","operationId":"patchJobsJobIdCandidatesUserIdInterested","tag":"Jobs","pathParams":["jobId","userId"],"bodyKind":"json","multipartFileField":null},
  "postNegotiations": {"path":"/negotiations","openapiPath":"/negotiations","method":"POST","operationId":"postNegotiations","tag":"Negotiations","pathParams":[],"bodyKind":"json","multipartFileField":null},
  "getNegotiationsMe": {"path":"/negotiations/me","openapiPath":"/negotiations/me","method":"GET","operationId":"getNegotiationsMe","tag":"Negotiations","pathParams":[],"bodyKind":null,"multipartFileField":null},
  "patchNegotiationsMeDecision": {"path":"/negotiations/me/decision","openapiPath":"/negotiations/me/decision","method":"PATCH","operationId":"patchNegotiationsMeDecision","tag":"Negotiations","pathParams":[],"bodyKind":"json","multipartFileField":null},
};

function isFileLike(value) {
  return value instanceof Blob || value instanceof File;
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !(value instanceof Date) && !isFileLike(value) && !Array.isArray(value) && !(value instanceof FormData);
}

function appendQuery(searchParams, prefix, value) {
  if (value === undefined || value === null) return;

  if (Array.isArray(value)) {
    value.forEach((item) => appendQuery(searchParams, prefix, item));
    return;
  }

  if (isPlainObject(value)) {
    Object.entries(value).forEach(([key, nestedValue]) => {
      appendQuery(searchParams, prefix ? `${prefix}.${key}` : key, nestedValue);
    });
    return;
  }

  searchParams.append(prefix, String(value));
}

function buildUrl(baseUrl, routePath, pathParams = {}, query) {
  const interpolatedPath = routePath.replace(/:([A-Za-z0-9_]+)/g, (_, key) => {
    const value = pathParams?.[key];

    if (value === undefined || value === null) {
      throw new Error(`Missing path parameter: ${key}`);
    }

    return encodeURIComponent(String(value));
  });

  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  const url = new URL(interpolatedPath, normalizedBaseUrl);

  if (query && typeof query === "object") {
    Object.entries(query).forEach(([key, value]) => {
      appendQuery(url.searchParams, key, value);
    });
  }

  return url.toString();
}

function safeParse(text) {
  if (!text) return null;

  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

function getErrorMessage(payload, fallback) {
  if (!payload) return fallback;
  if (typeof payload === "string") return payload;
  if (typeof payload === "object") {
    return payload.error || payload.message || fallback;
  }
  return fallback;
}

function appendFormData(formData, key, value) {
  if (value === undefined || value === null) return;

  if (Array.isArray(value)) {
    value.forEach((item) => appendFormData(formData, key, item));
    return;
  }

  if (isPlainObject(value)) {
    Object.entries(value).forEach(([nestedKey, nestedValue]) => {
      appendFormData(formData, key ? `${key}.${nestedKey}` : nestedKey, nestedValue);
    });
    return;
  }

  if (isFileLike(value)) {
    formData.append(key, value);
    return;
  }

  formData.append(key, String(value));
}

function toFormData(body, fileField) {
  if (body instanceof FormData) {
    return body;
  }

  const formData = new FormData();

  if (isFileLike(body)) {
    formData.append(fileField || "file", body);
    return formData;
  }

  if (isPlainObject(body)) {
    Object.entries(body).forEach(([key, value]) => {
      appendFormData(formData, key, value);
    });
    return formData;
  }

  if (body !== undefined && body !== null) {
    formData.append(fileField || "file", String(body));
  }

  return formData;
}

function buildRequestBody(body, headers, routeMeta) {
  if (body === undefined || body === null) {
    return undefined;
  }

  if (routeMeta?.bodyKind === "multipart") {
    return toFormData(body, routeMeta.multipartFileField);
  }

  if (body instanceof FormData) {
    return body;
  }

  if (isFileLike(body)) {
    return body;
  }

  headers.set("Content-Type", "application/json");
  return JSON.stringify(body);
}

export function createApiClient({ baseUrl = DEFAULT_BACKEND_URL, getToken } = {}) {
  async function request({ operationId, path, method, pathParams, query, body, headers: customHeaders = {}, token, signal, ...rest } = {}) {
    const headers = new Headers(customHeaders);
    const routeMeta = operationId ? routeManifest[operationId] : undefined;
    const resolvedToken = token ?? getToken?.();

    if (resolvedToken && !headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${resolvedToken}`);
    }

    const response = await fetch(buildUrl(baseUrl, path, pathParams, query), {
      method,
      headers,
      body: buildRequestBody(body, headers, routeMeta),
      signal,
      ...rest,
    });

    const raw = await response.text();
    const payload = safeParse(raw);

    if (!response.ok) {
      const error = new Error(getErrorMessage(payload, `Request failed with status ${response.status}`));
      error.status = response.status;
      error.payload = payload;
      throw error;
    }

    return payload;
  }

  return {
    request,
    patchSystemResetCooldown: (options = {}) => request({
      operationId: "patchSystemResetCooldown",
      path: "/system/reset-cooldown",
      method: "PATCH",
      ...options,
    }),

    patchSystemAvailabilityTimeout: (options = {}) => request({
      operationId: "patchSystemAvailabilityTimeout",
      path: "/system/availability-timeout",
      method: "PATCH",
      ...options,
    }),

    patchSystemJobStartWindow: (options = {}) => request({
      operationId: "patchSystemJobStartWindow",
      path: "/system/job-start-window",
      method: "PATCH",
      ...options,
    }),

    patchSystemNegotiationWindow: (options = {}) => request({
      operationId: "patchSystemNegotiationWindow",
      path: "/system/negotiation-window",
      method: "PATCH",
      ...options,
    }),

    postAuthResetsResetToken: (options = {}) => request({
      operationId: "postAuthResetsResetToken",
      path: "/auth/resets/:resetToken",
      method: "POST",
      ...options,
    }),

    postAuthResets: (options = {}) => request({
      operationId: "postAuthResets",
      path: "/auth/resets",
      method: "POST",
      ...options,
    }),

    postAuthTokens: (options = {}) => request({
      operationId: "postAuthTokens",
      path: "/auth/tokens",
      method: "POST",
      ...options,
    }),

    postUsers: (options = {}) => request({
      operationId: "postUsers",
      path: "/users",
      method: "POST",
      ...options,
    }),

    getUsers: (options = {}) => request({
      operationId: "getUsers",
      path: "/users",
      method: "GET",
      ...options,
    }),

    getUsersMe: (options = {}) => request({
      operationId: "getUsersMe",
      path: "/users/me",
      method: "GET",
      ...options,
    }),

    putUsersMeAvatar: (options = {}) => request({
      operationId: "putUsersMeAvatar",
      path: "/users/me/avatar",
      method: "PUT",
      ...options,
    }),

    putUsersMeResume: (options = {}) => request({
      operationId: "putUsersMeResume",
      path: "/users/me/resume",
      method: "PUT",
      ...options,
    }),

    patchUsersUserIdSuspended: (options = {}) => request({
      operationId: "patchUsersUserIdSuspended",
      path: "/users/:userId/suspended",
      method: "PATCH",
      ...options,
    }),

    patchUsersMe: (options = {}) => request({
      operationId: "patchUsersMe",
      path: "/users/me",
      method: "PATCH",
      ...options,
    }),

    patchUsersMeAvailable: (options = {}) => request({
      operationId: "patchUsersMeAvailable",
      path: "/users/me/available",
      method: "PATCH",
      ...options,
    }),

    getUsersMeInvitations: (options = {}) => request({
      operationId: "getUsersMeInvitations",
      path: "/users/me/invitations",
      method: "GET",
      ...options,
    }),

    getUsersMeInterests: (options = {}) => request({
      operationId: "getUsersMeInterests",
      path: "/users/me/interests",
      method: "GET",
      ...options,
    }),

    getUsersMeQualifications: (options = {}) => request({
      operationId: "getUsersMeQualifications",
      path: "/users/me/qualifications",
      method: "GET",
      ...options,
    }),

    postBusinesses: (options = {}) => request({
      operationId: "postBusinesses",
      path: "/businesses",
      method: "POST",
      ...options,
    }),

    getBusinesses: (options = {}) => request({
      operationId: "getBusinesses",
      path: "/businesses",
      method: "GET",
      ...options,
    }),

    getBusinessesMe: (options = {}) => request({
      operationId: "getBusinessesMe",
      path: "/businesses/me",
      method: "GET",
      ...options,
    }),

    patchBusinessesMe: (options = {}) => request({
      operationId: "patchBusinessesMe",
      path: "/businesses/me",
      method: "PATCH",
      ...options,
    }),

    getBusinessesMeJobs: (options = {}) => request({
      operationId: "getBusinessesMeJobs",
      path: "/businesses/me/jobs",
      method: "GET",
      ...options,
    }),

    postBusinessesMeJobs: (options = {}) => request({
      operationId: "postBusinessesMeJobs",
      path: "/businesses/me/jobs",
      method: "POST",
      ...options,
    }),

    patchBusinessesMeJobsJobId: (options = {}) => request({
      operationId: "patchBusinessesMeJobsJobId",
      path: "/businesses/me/jobs/:jobId",
      method: "PATCH",
      ...options,
    }),

    deleteBusinessesMeJobsJobId: (options = {}) => request({
      operationId: "deleteBusinessesMeJobsJobId",
      path: "/businesses/me/jobs/:jobId",
      method: "DELETE",
      ...options,
    }),

    putBusinessesMeAvatar: (options = {}) => request({
      operationId: "putBusinessesMeAvatar",
      path: "/businesses/me/avatar",
      method: "PUT",
      ...options,
    }),

    getBusinessesBusinessId: (options = {}) => request({
      operationId: "getBusinessesBusinessId",
      path: "/businesses/:businessId",
      method: "GET",
      ...options,
    }),

    patchBusinessesBusinessIdVerified: (options = {}) => request({
      operationId: "patchBusinessesBusinessIdVerified",
      path: "/businesses/:businessId/verified",
      method: "PATCH",
      ...options,
    }),

    postPositionTypes: (options = {}) => request({
      operationId: "postPositionTypes",
      path: "/position-types",
      method: "POST",
      ...options,
    }),

    getPositionTypes: (options = {}) => request({
      operationId: "getPositionTypes",
      path: "/position-types",
      method: "GET",
      ...options,
    }),

    patchPositionTypesPositionTypeId: (options = {}) => request({
      operationId: "patchPositionTypesPositionTypeId",
      path: "/position-types/:positionTypeId",
      method: "PATCH",
      ...options,
    }),

    deletePositionTypesPositionTypeId: (options = {}) => request({
      operationId: "deletePositionTypesPositionTypeId",
      path: "/position-types/:positionTypeId",
      method: "DELETE",
      ...options,
    }),

    getQualifications: (options = {}) => request({
      operationId: "getQualifications",
      path: "/qualifications",
      method: "GET",
      ...options,
    }),

    postQualifications: (options = {}) => request({
      operationId: "postQualifications",
      path: "/qualifications",
      method: "POST",
      ...options,
    }),

    getQualificationsQualificationId: (options = {}) => request({
      operationId: "getQualificationsQualificationId",
      path: "/qualifications/:qualificationId",
      method: "GET",
      ...options,
    }),

    patchQualificationsQualificationId: (options = {}) => request({
      operationId: "patchQualificationsQualificationId",
      path: "/qualifications/:qualificationId",
      method: "PATCH",
      ...options,
    }),

    putQualificationsQualificationIdDocument: (options = {}) => request({
      operationId: "putQualificationsQualificationIdDocument",
      path: "/qualifications/:qualificationId/document",
      method: "PUT",
      ...options,
    }),

    getJobs: (options = {}) => request({
      operationId: "getJobs",
      path: "/jobs",
      method: "GET",
      ...options,
    }),

    getJobsJobId: (options = {}) => request({
      operationId: "getJobsJobId",
      path: "/jobs/:jobId",
      method: "GET",
      ...options,
    }),

    patchJobsJobIdNoShow: (options = {}) => request({
      operationId: "patchJobsJobIdNoShow",
      path: "/jobs/:jobId/no-show",
      method: "PATCH",
      ...options,
    }),

    patchJobsJobIdInterested: (options = {}) => request({
      operationId: "patchJobsJobIdInterested",
      path: "/jobs/:jobId/interested",
      method: "PATCH",
      ...options,
    }),

    getJobsJobIdInterests: (options = {}) => request({
      operationId: "getJobsJobIdInterests",
      path: "/jobs/:jobId/interests",
      method: "GET",
      ...options,
    }),

    getJobsJobIdCandidates: (options = {}) => request({
      operationId: "getJobsJobIdCandidates",
      path: "/jobs/:jobId/candidates",
      method: "GET",
      ...options,
    }),

    getJobsJobIdCandidatesUserId: (options = {}) => request({
      operationId: "getJobsJobIdCandidatesUserId",
      path: "/jobs/:jobId/candidates/:userId",
      method: "GET",
      ...options,
    }),

    patchJobsJobIdCandidatesUserIdInterested: (options = {}) => request({
      operationId: "patchJobsJobIdCandidatesUserIdInterested",
      path: "/jobs/:jobId/candidates/:userId/interested",
      method: "PATCH",
      ...options,
    }),

    postNegotiations: (options = {}) => request({
      operationId: "postNegotiations",
      path: "/negotiations",
      method: "POST",
      ...options,
    }),

    getNegotiationsMe: (options = {}) => request({
      operationId: "getNegotiationsMe",
      path: "/negotiations/me",
      method: "GET",
      ...options,
    }),

    patchNegotiationsMeDecision: (options = {}) => request({
      operationId: "patchNegotiationsMeDecision",
      path: "/negotiations/me/decision",
      method: "PATCH",
      ...options,
    }),
  };
}
